narrow down jobs
Signed-off-by: Brian Vander Schaaf <6099457+bvand@users.noreply.github.com>

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -140,103 +140,103 @@ jobs:
         run: |
           TF_ACC=1 go test -v ./internal/command/e2etest
 
-  consistency-checks:
-    name: "Code Consistency Checks"
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: "Fetch source code"
-        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-        with:
-          fetch-depth: 0 # We need to do comparisons against the main branch.
-
-      - name: Determine Go version
-        id: go
-        uses: ./.github/actions/go-version
-
-      - name: Install Go toolchain
-        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
-        with:
-          go-version: ${{ steps.go.outputs.version }}
-
-      # NOTE: This cache is shared so the following step must always be
-      # identical across the unit-tests, e2e-tests, and consistency-checks
-      # jobs, or else weird things could happen.
-      - name: Cache Go modules
-        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
-        with:
-          path: "~/go/pkg"
-          key: go-mod-${{ hashFiles('go.sum') }}
-          restore-keys: |
-            go-mod-
-
-      - name: "go.mod and go.sum consistency check"
-        run: |
-          go mod tidy
-          if [[ -n "$(git status --porcelain)" ]]; then
-            echo >&2 "ERROR: go.mod/go.sum are not up-to-date. Run 'go mod tidy' and then commit the updated files."
-            exit 1
-          fi
-
-      - name: Cache protobuf tools
-        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
-        with:
-          path: "tools/protobuf-compile/.workdir"
-          key: protobuf-tools-${{ hashFiles('tools/protobuf-compile/protobuf-compile.go') }}
-          restore-keys: |
-            protobuf-tools-
-
-      - name: "Code consistency checks"
-        run: |
-          make fmtcheck importscheck generate staticcheck exhaustive protobuf
-          if [[ -n "$(git status --porcelain)" ]]; then
-            echo >&2 "ERROR: Generated files are inconsistent. Run 'make generate' and 'make protobuf' locally and then commit the updated files."
-            git >&2 status --porcelain
-            exit 1
-          fi
-
-  license-checks:
-    name: "License Checks"
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: "Fetch source code"
-        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
-
-      - name: Install licensei
-        run: |
-          make deps
-
-      - name: Restore cache license information of dependencies
-        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
-        with:
-          path: ".licensei.cache"
-          key: licensei-cache-${{ hashFiles('go.sum') }}
-          restore-keys: |
-            licensei-cache-
-
-      - name: Determine Go version
-        id: go
-        uses: ./.github/actions/go-version
-
-      - name: Install Go toolchain
-        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
-        with:
-          go-version: ${{ steps.go.outputs.version }}
-
-      - name: Run licensei
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          make license-check
-        if: env.LICENSE_CHECK != 'false'
-
-      - name: Save cache license information of dependencies
-        uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
-        if: always()
-        with:
-          path: ".licensei.cache"
-          key: licensei-cache-${{ hashFiles('go.sum') }}
+#  consistency-checks:
+#    name: "Code Consistency Checks"
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: "Fetch source code"
+#        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+#        with:
+#          fetch-depth: 0 # We need to do comparisons against the main branch.
+#
+#      - name: Determine Go version
+#        id: go
+#        uses: ./.github/actions/go-version
+#
+#      - name: Install Go toolchain
+#        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
+#        with:
+#          go-version: ${{ steps.go.outputs.version }}
+#
+#      # NOTE: This cache is shared so the following step must always be
+#      # identical across the unit-tests, e2e-tests, and consistency-checks
+#      # jobs, or else weird things could happen.
+#      - name: Cache Go modules
+#        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+#        with:
+#          path: "~/go/pkg"
+#          key: go-mod-${{ hashFiles('go.sum') }}
+#          restore-keys: |
+#            go-mod-
+#
+#      - name: "go.mod and go.sum consistency check"
+#        run: |
+#          go mod tidy
+#          if [[ -n "$(git status --porcelain)" ]]; then
+#            echo >&2 "ERROR: go.mod/go.sum are not up-to-date. Run 'go mod tidy' and then commit the updated files."
+#            exit 1
+#          fi
+#
+#      - name: Cache protobuf tools
+#        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+#        with:
+#          path: "tools/protobuf-compile/.workdir"
+#          key: protobuf-tools-${{ hashFiles('tools/protobuf-compile/protobuf-compile.go') }}
+#          restore-keys: |
+#            protobuf-tools-
+#
+#      - name: "Code consistency checks"
+#        run: |
+#          make fmtcheck importscheck generate staticcheck exhaustive protobuf
+#          if [[ -n "$(git status --porcelain)" ]]; then
+#            echo >&2 "ERROR: Generated files are inconsistent. Run 'make generate' and 'make protobuf' locally and then commit the updated files."
+#            git >&2 status --porcelain
+#            exit 1
+#          fi
+#
+#  license-checks:
+#    name: "License Checks"
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: "Fetch source code"
+#        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+#
+#      - name: Install licensei
+#        run: |
+#          make deps
+#
+#      - name: Restore cache license information of dependencies
+#        uses: actions/cache/restore@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+#        with:
+#          path: ".licensei.cache"
+#          key: licensei-cache-${{ hashFiles('go.sum') }}
+#          restore-keys: |
+#            licensei-cache-
+#
+#      - name: Determine Go version
+#        id: go
+#        uses: ./.github/actions/go-version
+#
+#      - name: Install Go toolchain
+#        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
+#        with:
+#          go-version: ${{ steps.go.outputs.version }}
+#
+#      - name: Run licensei
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        run: |
+#          make license-check
+#        if: env.LICENSE_CHECK != 'false'
+#
+#      - name: Save cache license information of dependencies
+#        uses: actions/cache/save@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+#        if: always()
+#        with:
+#          path: ".licensei.cache"
+#          key: licensei-cache-${{ hashFiles('go.sum') }}
 
 #  installation-instructions:
 #    name: "Test Installation Instructions"
