add automated copyright header check (#1696)
Signed-off-by: ollevche <ollevche@gmail.com>
Signed-off-by: Oleksandr Levchenkov <ollevche@gmail.com>
Signed-off-by: David Sims <simsdj82@gmail.com>

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -214,6 +214,14 @@ jobs:
         with:
           version: v1.58
           only-new-issues: true
+      
+      - name: "Copyright headers"
+        run: |
+          go run github.com/hashicorp/copywrite headers --plan
+          if [[ $? != 0 ]]; then
+            echo >&2 "ERROR: some files are missing required copyright headers. Run `scripts/add-copyright-headers.sh` locally and then commit the updated files."
+            exit 1
+          fi
 
   license-checks:
     name: "License Checks"
