add github check for missing copyright headers
Signed-off-by: ollevche <ollevche@gmail.com>

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -214,6 +214,12 @@ jobs:
         with:
           version: v1.58
           only-new-issues: true
+      
+      - name: "Copyright headers"
+        run: |
+          if [[ ! (go run github.com/hashicorp/copywrite headers --plan) ]]; then
+            echo >&2 "ERROR: some files are missing required copyright headers"
+          fi
 
   license-checks:
     name: "License Checks"
